class Config:
    def __init__(self):
        self.PATH = "data"
        self.submissions_path = "submissions"
        self.LOG_FEATS =      ['LOG_DATA_VOLUME', 'LOG_REVENUE', 'LOG_MONTANT']

        self.MEAN_FEATS =     ['DATA_VOLUME_REGION_MEAN', 'FREQUENCE_RECH_REGION_MEAN', 'ON_NET_REGION_MEAN', 'MONTANT_REGION_MEAN', 'REVENUE_REGION_MEAN', 'FREQ_REGION_MEAN', 
                               'REG_REGION_MEAN', 'ORANGE_REGION_MEAN', 'TIGO_REGION_MEAN', 'FREQ_TOP_PACK_REGION_MEAN', 'DATA_VOLUME_TENURE_MEAN', 'FREQUENCE_RECH_TENURE_MEAN', 
                               'ON_NET_TENURE_MEAN', 'MONTANT_TENURE_MEAN', 'REVENUE_TENURE_MEAN', 'FREQ_TENURE_MEAN', 'REG_TENURE_MEAN', 'ORANGE_TENURE_MEAN', 'TIGO_TENURE_MEAN', 
                               'FREQ_TOP_PACK_TENURE_MEAN', 'DATA_VOLUME_TOP_PACK_MEAN', 'FREQUENCE_RECH_TOP_PACK_MEAN', 'ON_NET_TOP_PACK_MEAN', 'MONTANT_TOP_PACK_MEAN', 'REVENUE_TOP_PACK_MEAN', 
                               'FREQ_TOP_PACK_MEAN', 'REG_TOP_PACK_MEAN', 'ORANGE_TOP_PACK_MEAN', 'TIGO_TOP_PACK_MEAN', 'FREQ_TOP_PACK_TOP_PACK_MEAN', 'DATA_VOLUME_UNLIMITED_CALL_MEAN', 
                               'FREQUENCE_RECH_UNLIMITED_CALL_MEAN', 'ON_NET_UNLIMITED_CALL_MEAN', 'MONTANT_UNLIMITED_CALL_MEAN', 'REVENUE_UNLIMITED_CALL_MEAN', 'FREQ_UNLIMITED_CALL_MEAN', 
                               'REG_UNLIMITED_CALL_MEAN', 'ORANGE_UNLIMITED_CALL_MEAN', 'TIGO_UNLIMITED_CALL_MEAN', 'FREQ_TOP_PACK_UNLIMITED_CALL_MEAN']

        self.DIFF_MEAN_FEATS = ['DIFF_DV_MEAN_REGION', 'DIFF_FR_MEAN_REGION', 'DIFF_ON_NET_MEAN_REGION', 'DIFF_MT_MEAN_REGION', 'DIFF_RV_MEAN_REGION', 'DIFF_FREQ_MEAN_REGION', 
                               'DIFF_REG_MEAN_REGION', 'DIFF_ORG_MEAN_REGION', 'DIFF_TIGO_MEAN_REGION', 'DIFF_FREQ_TOP_PACK_MEAN_REGION', 'DIFF_DV_MEAN_TENURE', 'DIFF_FR_MEAN_TENURE', 
                               'DIFF_ON_NET_MEAN_TENURE', 'DIFF_MT_MEAN_TENURE', 'DIFF_RV_MEAN_TENURE', 'DIFF_FREQ_MEAN_TENURE', 'DIFF_REG_MEAN_TENURE', 'DIFF_ORG_MEAN_TENURE', 
                               'DIFF_TIGO_MEAN_TENURE', 'DIFF_FREQ_TOP_PACK_MEAN_TENURE', 'DIFF_DV_MEAN_TOP_PACK', 'DIFF_FR_MEAN_TOP_PACK', 'DIFF_ON_NET_MEAN_TOP_PACK', 'DIFF_MT_MEAN_TOP_PACK', 
                               'DIFF_RV_MEAN_TOP_PACK', 'DIFF_FREQ_MEAN_TOP_PACK', 'DIFF_REG_MEAN_TOP_PACK', 'DIFF_ORG_MEAN_TOP_PACK', 'DIFF_TIGO_MEAN_TOP_PACK', 'DIFF_FREQ_TOP_PACK_MEAN_TOP_PACK', 
                               'DIFF_DV_MEAN_UNLIMITED_CALL', 'DIFF_FR_MEAN_UNLIMITED_CALL', 'DIFF_ON_NET_MEAN_UNLIMITED_CALL', 'DIFF_MT_MEAN_UNLIMITED_CALL', 'DIFF_RV_MEAN_UNLIMITED_CALL', 'DIFF_FREQ_MEAN_UNLIMITED_CALL', 
                               'DIFF_REG_MEAN_UNLIMITED_CALL', 'DIFF_ORG_MEAN_UNLIMITED_CALL', 'DIFF_TIGO_MEAN_UNLIMITED_CALL', 'DIFF_FREQ_TOP_PACK_MEAN_UNLIMITED_CALL']

        self.DIFF_QRTLS_FEATS = ['DIFF_ON_NET_Q1_TENURE', 'DIFF_ON_NET_Q3_TENURE', 'DIFF_MONTANT_Q1_TENURE', 'DIFF_MONTANT_Q3_TENURE', 'DIFF_ORANGE_Q1_TENURE', 'DIFF_ORANGE_Q3_TENURE', 'DIFF_TIGO_Q1_TENURE', 'DIFF_TIGO_Q3_TENURE', 
                                 'DIFF_REGULARITY_Q1_TENURE', 'DIFF_REGULARITY_Q3_TENURE', 'DIFF_FREQ_TOP_PACK_Q1_TENURE', 'DIFF_FREQ_TOP_PACK_Q3_TENURE', 'DIFF_FREQUENCE_RECH_Q1_TENURE', 'DIFF_FREQUENCE_RECH_Q3_TENURE', 
                                 'DIFF_FREQUENCE_Q1_TENURE', 'DIFF_FREQUENCE_Q3_TENURE', 'DIFF_DATA_VOLUME_Q1_TENURE', 'DIFF_DATA_VOLUME_Q3_TENURE']

        self.NN_FEATS =         ['REGION', 'TENURE', 'TOP_PACK', 'REGION_TENURE', 'UNLIMITED_CALL', 'FORFAIT_24h', 'FORFAIT_5d', 'FORFAIT_7d',
                                'TE_REGION', 'TE_TENURE', 'TE_TOP_PACK', 'TE_REGION_TENURE', 'TE_REGION_TOP_PACK', 'TE_TENURE_TOP_PACK', 'REGULARITY',
                                'N_MISSING', 'N_MISSING_OP', 'N_MISSING_REV', 'N_MISSING_ZONE', 'N_MISSING_PACK', 'N_MISSING_FREQ_DT', 'N_MISSING_IDENTITY']